config:
  rpc:
    host: ${RPC_HOST}
    username: ${RPC_USERNAME}
    password: ${RPC_PASSWORD}
    port: ${RPC_PORT}

server:
  servlet:
      context-path: /mscambio
  port: ${port:8080}

management:
  endpoints:
    web:
      base-path: /
