version: "3.3"

services:
  sonarqube:
    image: sonarqube:8.4.2-community
    expose:
      - 9000
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - sonarnet
    volumes:
      - /opt/sonarqube/lib/bundled-plugins:/tmp/sonarqube/lib/bundled-plugins
      - /opt/sonarqube/conf:/tmp/sonarqube/conf
      - /opt/sonarqube/data:/tmp/sonarqube/data
      - /opt/sonarqube/extensions:/tmp/sonarqube/extensions
networks:
  sonarnet:

